name: Backup testnets

on:
  # Triggers the workflow every day at 1am
  schedule:
    - cron: "0 1 * * *"

jobs:
  backup:
    name: "backup ${{ matrix.testnet }}"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        testnet:
          - test2.gno.land
          - test3.gno.land

    steps:
      - uses: actions/checkout@v4

      - name: Run backup script
        run: make -C ${{ matrix.testnet }} fetch

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ${{ matrix.testnet }} backup"
